# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Cloud2DImageConverter',
                'doc_host': 'https://alunos-pfc.github.io',
                'git_url': 'https://github.com/alunos-pfc/Cloud2DImageConverter',
                'lib_path': 'Cloud2DImageConverter'},
  'syms': {'Cloud2DImageConverter.core': {'Cloud2DImageConverter.core.foo': ('core.html#foo', 'Cloud2DImageConverter/core.py')}}}
